### ISSUE TITLE
[Form] Migrate to TypeScript

### ISSUE THREAD

**Issue by xballoy** [AxaGuilDEv/react-toolkit#394]
In order to solve #391 we need to convert the form package to TypeScript.

List of packages to migrate:

- [x] @axa-fr/react-toolkit-form-core - ref PR #709 
- [ ] @axa-fr/react-toolkit-form-filter - Duplicate of #749 
- [ ] @axa-fr/react-toolkit-form-filter-inline - Duplicate of #750 
- [ ] @axa-fr/react-toolkit-form-input-card - Duplicate of #751 
- [ ] @axa-fr/react-toolkit-form-input-checkbox - Duplicate of #752 
- [ ] @axa-fr/react-toolkit-form-input-choice - Duplicate of #753 
- [ ] @axa-fr/react-toolkit-form-input-date
- [ ] @axa-fr/react-toolkit-form-input-file - Duplicate of #754 
- [ ] @axa-fr/react-toolkit-form-input-number
- [ ] @axa-fr/react-toolkit-form-input-radio - Duplicate of #755 
- [ ] @axa-fr/react-toolkit-form-input-select - Duplicate of #756 
- [ ] @axa-fr/react-toolkit-form-input-select-multi -  - Duplicate of #757 
- [ ] @axa-fr/react-toolkit-form-input-slider - Duplicate of #758 
- [ ] @axa-fr/react-toolkit-form-input-switch - Duplicate of #759 
- [ ] @axa-fr/react-toolkit-form-input-text - Duplicate of #760 
- [ ] @axa-fr/react-toolkit-form-input-textarea - Duplicate of #761 
- [ ] @axa-fr/react-toolkit-form-steps - Duplicate of #762 
- [x] @axa-fr/react-toolkit-form-summary

**Comment by xballoy** [comment]
Ping @samuel-gomez-axa / @guillaumechervetaxa 
Can you assign me to this issue and create a branch `feature/migrateForm` so I can push several PR for each package instead of a big one?
Thanks!

**Comment by xballoy** [comment]
Are the packages `react-toolkit-form-filter` and `react-toolkit-form-filter-inline` still relevant ? They just display a div 🧐.
If not maybe I can remove them. What do you think?

**Comment by arnaudforaison** [comment]
These packages exist because they need there implementation.
So don't remove it.

It's huge to migrate all form components, so maybe split it on single issue for each components.

And then some people can assign it

**Comment by xballoy** [comment]
I close this one as we created dedicated issues for all packages
